[ellar]
default = "todo"
[ellar.projects.todo]
project-name = "todo"
application = "todo.server:application"
config = "todo.config:DevelopmentConfig"
root-module = "todo.root_module:ApplicationModule"
